### ISSUE TITLE
Errors reading values

### ISSUE THREAD

**Issue by AtarianComputing** [oxynic/Inverter.homeassistant.MQTT#1]
Hi,

After tearing my head trying to get the Docker thing to work, I was happy to find your potential solution. It seems everything is working fine even up to MQTT but I seem to get parsing errors or something. Can you make anything out of this? No HTML file was generated.

![image](https://user-images.githubusercontent.com/29645247/114674339-caf42400-9d0f-11eb-8e40-9c6245bf4983.png)

Debug - 14.4.2021 10.02.11 - 
:Write - 51 4D 4F 44 49 C1 0D 

Debug - 14.4.2021 10.02.11 - 
:HRead - 28 42 E7 C9 0D 

Debug - 14.4.2021 10.02.11 - 
:CRead - (BçÉ

Debug - 14.4.2021 10.02.12 - 
:Managed client started.

Debug - 14.4.2021 10.02.14 - 
:Write - 51 50 49 47 53 B7 A9 0D 

Debug - 14.4.2021 10.02.14 - 
:HRead - 28 32 33 32 2E 30 20 35 

Debug - 14.4.2021 10.02.14 - 
:HRead - 30 2E 31 20 32 32 38 2E 

Debug - 14.4.2021 10.02.14 - 
:HRead - 30 20 35 30 2E 32 20 30 

Debug - 14.4.2021 10.02.14 - 
:HRead - 31 31 33 20 30 31 31 33 

Debug - 14.4.2021 10.02.14 - 
:HRead - 20 30 30 34 20 34 31 31 

Debug - 14.4.2021 10.02.15 - 
:HRead - 20 32 36 2E 34 37 20 30 

Debug - 14.4.2021 10.02.15 - 
:HRead - 30 30 20 30 38 36 20 30 

Debug - 14.4.2021 10.02.15 - 
:HRead - 35 34 33 20 30 30 30 32 

Debug - 14.4.2021 10.02.15 - 
:HRead - 20 30 33 38 2E 30 20 32 

Debug - 14.4.2021 10.02.15 - 
:HRead - 36 2E 36 33 20 30 30 30 

Debug - 14.4.2021 10.02.15 - 
:HRead - 30 35 20 31 30 30 31 30 

Debug - 14.4.2021 10.02.15 - 
:HRead - 31 31 30 20 30 30 20 30 

Debug - 14.4.2021 10.02.15 - 
:HRead - 34 20 30 30 30 39 31 20 

Debug - 14.4.2021 10.02.15 - 
:HRead - 30 30 30 39 76 0D 

Debug - 14.4.2021 10.02.15 - 
:   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToSingle(String value)
   at Inverter.homeassistant.MQTT.Inverter.PopulateData(String data)
   at Inverter.homeassistant.MQTT.Inverter.ProcessRead()

**Comment by abouelfouz** [comment]
Hi Atarian, indeed its a saver; did you manage to solve your issue above as i am having the same? kind regards

**Comment by abouelfouz** [comment]
i solved by creating a batch file that starts the exe file and after 1 hour closes and reopens, this way it does not crash.
@echo off
cls
:start
START C:\Users\Zahra\Documents\Inverter.homeassistant.MQTT-master\bin\Debug\Inverter.homeassistant.MQTT.exe
TIMEOUT 5000
TASKKILL /F /IM Inverter.homeassistant.MQTT.exe
goto start

**Comment by Minion-1** [comment]
> Hi,
> 
> After tearing my head trying to get the Docker thing to work, I was happy to find your potential solution. It seems everything is working fine even up to MQTT but I seem to get parsing errors or something. Can you make anything out of this? No HTML file was generated.
> 
> ![image](https://user-images.githubusercontent.com/29645247/114674339-caf42400-9d0f-11eb-8e40-9c6245bf4983.png)
> 
> Debug - 14.4.2021 10.02.11 - :Write - 51 4D 4F 44 49 C1 0D
> 
> Debug - 14.4.2021 10.02.11 - :HRead - 28 42 E7 C9 0D
> 
> Debug - 14.4.2021 10.02.11 - :CRead - (BçÉ
> 
> Debug - 14.4.2021 10.02.12 - :Managed client started.
> 
> Debug - 14.4.2021 10.02.14 - :Write - 51 50 49 47 53 B7 A9 0D
> 
> Debug - 14.4.2021 10.02.14 - :HRead - 28 32 33 32 2E 30 20 35
> 
> Debug - 14.4.2021 10.02.14 - :HRead - 30 2E 31 20 32 32 38 2E
> 
> Debug - 14.4.2021 10.02.14 - :HRead - 30 20 35 30 2E 32 20 30
> 
> Debug - 14.4.2021 10.02.14 - :HRead - 31 31 33 20 30 31 31 33
> 
> Debug - 14.4.2021 10.02.14 - :HRead - 20 30 30 34 20 34 31 31
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 20 32 36 2E 34 37 20 30
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 30 30 20 30 38 36 20 30
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 35 34 33 20 30 30 30 32
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 20 30 33 38 2E 30 20 32
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 36 2E 36 33 20 30 30 30
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 30 35 20 31 30 30 31 30
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 31 31 30 20 30 30 20 30
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 34 20 30 30 30 39 31 20
> 
> Debug - 14.4.2021 10.02.15 - :HRead - 30 30 30 39 76 0D
> 
> Debug - 14.4.2021 10.02.15 - : at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt) at System.Convert.ToSingle(String value) at Inverter.homeassistant.MQTT.Inverter.PopulateData(String data) at Inverter.homeassistant.MQTT.Inverter.ProcessRead()

I am facing the exact same issue on a Voltronic Infini 3KW. MQTT connects but no data.
